Changes
MariaChizhova/Mind-Map pull request #11
Opened 2020-03-03 23:30 UTC by MariaChizhova

Тут нужно бы еще посмотреть то, что в мастер мы залили без ревью кода

2020-03-04 09:12 UTC, OlesiaSub approved these changes

2020-03-04 09:23 UTC, Hotckiss requested changes

2020-03-04 09:23 UTC, Hotckiss commented on src/menu.cpp
> +    /** TO DO: Вставить цвет из Svgreader */
силион подсвечивает красиво слитное todo

2020-03-04 09:23 UTC, Hotckiss commented on src/menu.cpp
> +    newFileButton();
такое, лучше тогда отдельный метод завести с норм названием и дергать его по разным нажатиям

2020-03-04 09:23 UTC, Hotckiss commented on src/svgreader.cpp
> +            qreal m11 = trans.m11();    /** Horizontal scaling */
я бы эту всю тему вынес в отдельный метод

зачем присваивать 6 переменных а ниже сразу переприсваивать?

2020-03-04 09:23 UTC, Hotckiss commented on src/svgreader.cpp
> +            if (rectangle.attribute("x").toInt() == 0 &&
потом это надо как-то переделать

2020-03-04 11:08 UTC, OlesiaSub submitted a review, later dismissed

2020-03-04 12:47 UTC, MariaChizhova commented on src/menu.cpp
> +    /** TO DO: Вставить цвет из Svgreader */
Ок

2020-03-04 12:49 UTC, MariaChizhova commented on src/menu.cpp
> +    newFileButton();
Сделано

2020-03-04 12:52 UTC, MariaChizhova commented on src/svgreader.cpp
> +            qreal m11 = trans.m11();    /** Horizontal scaling */
В отдельный метод позже вынесу, потому что скорее всего еще подкорректирую функцию.
С переприсваиванием исправила.

2020-03-04 12:53 UTC, MariaChizhova commented on src/svgreader.cpp
> +            if (rectangle.attribute("x").toInt() == 0 &&
Да, пока непоятно как, пусть временно так побудет

2020-03-04 18:32 UTC, MariaChizhova commented on src/svgreader.cpp
> +            if (rectangle.attribute("x").toInt() == 0 &&
Тут надо научиться получать размеры scene, а потом не добавлять сам фон, как элемент прямоугольника

2020-03-07 21:40 UTC, Hotckiss approved these changes

2020-03-07 21:43 UTC, merged