Changes
MariaChizhova/Mind-Map pull request #3
Opened 2020-02-26 08:30 UTC by MariaChizhova

2020-02-26 10:29 UTC, Hotckiss requested changes

2020-02-26 10:29 UTC, Hotckiss commented on src/menu.cpp
> +    /** Добавляем сцену в основное окно */
почему `newFileButton` делает вот это?
```
view.setScene(&scene);
setCentralWidget(&view);
```

2020-02-26 10:29 UTC, Hotckiss commented on src/scene.cpp
> +    m_activeItem = new QGraphicsRectItem(event->lastPos().rx() - 30, event->lastPos().ry() - 20, 60, 40);
магических констант лучше избегать, потому что надо задумываться, что это какой-то сдвиг относительно позиции курсора, и появляются вопросы "почему сдвиг такой, а не другой"
Я бы тогда завел 
```
int width = 60;
int height = 40;
int originX = event->lastPos().rx() - width / 2;
int originY = event->lastPos().ry() - height / 2;
m_activeItem = new QGraphicsRectItem(originX, originY, width, height);
```

Понятно, что сейчас это просто как пример работы, но потом лучше заводить например 
`const int CONSTANT = 30;`

2020-02-26 10:29 UTC, Hotckiss commented on src/scene.cpp
> +    if (!m_activeItem) return;
Лучше на отдельной строчке все-таки, чтобы, например, можно было поставить breakpoint в дебаггере на этот `return;`

2020-02-26 10:33 UTC, MariaChizhova commented on src/menu.cpp
> +    /** Добавляем сцену в основное окно */
Потому что сначала ничего нет, а когда нажимается new file, то добавляется белый фон + уже возможность что-то делать

2020-02-26 10:52 UTC, MariaChizhova commented on src/scene.cpp
> +    m_activeItem = new QGraphicsRectItem(event->lastPos().rx() - 30, event->lastPos().ry() - 20, 60, 40);
@Hotckiss, исправлено.

2020-02-26 10:53 UTC, MariaChizhova commented on src/scene.cpp
> +    if (!m_activeItem) return;
Исправлено.

2020-02-27 14:09 UTC, Hotckiss requested changes

2020-02-27 14:09 UTC, Hotckiss commented on src/menu.cpp
> +    QPixmap openpix("/home/maria/Mind-Map/icons/open.png");
не, такое нельзя мержить)

2020-02-27 14:09 UTC, Hotckiss commented on src/menu.cpp
> +    QPixmap openpix("/home/maria/Mind-Map/icons/open.png");
Предлагаю вот так:
CMakeLists.txt:
Добавить строчку:
`set(CMAKE_AUTORCC ON)`
и удалить 


```
configure_file(icons/new.png COPYONLY)
configure_file(icons/open.png COPYONLY)
configure_file(icons/help.png COPYONLY)
configure_file(icons/quit.png COPYONLY)
```

Завести файлик `resources.qrc` и в CMakeLists.txt его прилинковать к остальному:
`add_executable(project_hse ${src} resources.qrc)`

сам файлик с контентом:
```
<!DOCTYPE RCC><RCC version="1.0">
    <qresource>
        <file>icons/help.png</file>
        <file>icons/new.png</file>
        <file>icons/open.png</file>
        <file>icons/quit.png</file>
    </qresource>
</RCC>
```

Использовать так:
`QPixmap newpix(":/icons/new.png");`

Еще можно завести алиас в qrc:
`<file alias="quit">icons/quit.png</file>` и писать
`QPixmap newpix(":/quit");`

2020-02-27 15:16 UTC, MariaChizhova commented on src/menu.cpp
> +    QPixmap openpix("/home/maria/Mind-Map/icons/open.png");
Исправлено.

2020-02-27 18:35 UTC, Hotckiss approved these changes

2020-02-27 19:09 UTC, Karina5005 approved these changes
Вроде все ок)

2020-02-27 19:10 UTC, merged